<!DOCTYPE html>
<html lang="pl">
<head>
	<meta charset="utf-8" />
	<title>ATLAS TDAQ Publications</title>
	<link href="css/normalize.css" rel="stylesheet" />
	<link href="https://fonts.googleapis.com/css?family=Dosis" rel="stylesheet" />
    <link href="css/icons.css" rel="stylesheet" />
    <link href="css/style.css" rel="stylesheet" />
</head>
<body>

<nav id="app-nav">
    <ul id="app-menu" class="move-left">
        <li class="active"><a href="#">Projects</a></li>
        <li><a href="#">Recipients</a></li>
    </ul>
	<div id="google-signin" class="move-right"></div>
</nav>

<header id="app-header">
	<h1>CERN Publications</h1>
	<p class="description">Email management</p>
</header>

<main id="app-container">
	<div id="project-list"></div>
</main>

<footer id="app-footer">
	<p>Made by Kamil Drzazga</p>
</footer>

<script src="js/bundle.js"></script>
</body>
</html>