<!DOCTYPE html>
<html lang="pl">
<head>
	<meta charset="utf-8" />
	<title>ATLAS TDAQ Publications</title>
	<link href="css/normalize.css" rel="stylesheet" />
	<link href="https://fonts.googleapis.com/css?family=Dosis" rel="stylesheet" />
	<link href="css/style.css" rel="stylesheet" />
</head>
<body>

<nav id="app-nav">
	<div id="google-signin"></div>
</nav>

<header id="app-header">
	<h1>ATLAS TDAQ Publications</h1>
</header>

<main id="app-container">
	<p>Open project...</p>
	<div id="project-list"></div>
	<p>... or create new</p>
	<button>Create new project</button>
</main>

<footer id="app-footer">
	<p>Made by Kamil Drzazga</p>
</footer>

<script src="js/bundle.js"></script>
</body>
</html>