CREATE TABLE projects (
  id            INTEGER     NOT NULL PRIMARY KEY AUTO_INCREMENT,
  name          VARCHAR(40) NOT NULL UNIQUE,
  google_doc_id VARCHAR(40) NOT NULL,
  section       INTEGER,
  created_at    DATETIME    NOT NULL             DEFAULT CURRENT_TIMESTAMP,
  updated_at    DATETIME    NOT NULL             DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
